import type {
  AiAgent,
  AiCommand,
  AiConfiguration,
  AiInstruction,
  AiSkill,
  ProviderAdapter,
  ProviderId,
} from '@aiconfig/core';

import { createDefaultAdapters } from '../../src/index.js';

/**
 * Canonical artifacts built in memory, for tests that compile one artifact kind
 * at a time.
 *
 * The adapter fixture tests compile a real `.ai/` directory holding everything
 * at once, which is the right shape for checking generated bytes. The matrix
 * tests ask a different question — what does *this* kind produce on *that*
 * provider — and need each kind in isolation, without a directory per cell.
 */

export const instruction = (name: string, applyTo: readonly string[] = []): AiInstruction => ({
  name,
  description: `Description of ${name}`,
  applyTo,
  body: `Body of ${name}.`,
  sourcePath: `.ai/instructions/${name}.md`,
});

export const agent = (name: string): AiAgent => ({
  name,
  description: `Description of ${name}`,
  body: `System prompt of ${name}.`,
  sourcePath: `.ai/agents/${name}.md`,
});

export const command = (name: string): AiCommand => ({
  name,
  description: `Description of ${name}`,
  body: `Prompt of ${name}.`,
  sourcePath: `.ai/commands/${name}.md`,
});

export const skill = (name: string): AiSkill => ({
  name,
  description: `Description of ${name}`,
  files: [
    { relativePath: 'SKILL.md', sha256: `sha256:${name}-entrypoint`, size: 64, executable: false },
    {
      relativePath: 'references/checklist.md',
      sha256: `sha256:${name}-checklist`,
      size: 32,
      executable: false,
    },
  ],
  sourcePath: `.ai/skills/${name}`,
  entrypointText: `---\nname: ${name}\ndescription: Description of ${name}\n---\n\nSteps.\n`,
  entrypointKeys: ['name', 'description'],
});

export const EMPTY_CONFIGURATION: AiConfiguration = {
  instructions: [],
  agents: [],
  skills: [],
  commands: [],
};

export const configurationOf = (parts: Partial<AiConfiguration>): AiConfiguration => ({
  ...EMPTY_CONFIGURATION,
  ...parts,
});

const adapters = createDefaultAdapters();

export const adapterFor = (provider: ProviderId): ProviderAdapter => {
  const adapter = adapters.find((candidate) => candidate.id === provider);
  if (adapter === undefined) {
    throw new Error(`No adapter registered for '${provider}'.`);
  }
  return adapter;
};
