import * as fs from 'node:fs';
import * as fsp from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import type { ProviderId, SourceKind } from '@aiconfig/core';
import {
  MANIFEST_PATH,
  NodeFileSystem,
  clean,
  disableProvider,
  enableProvider,
  removeArtifact,
  restore,
} from '@aiconfig/core';
import { exampleRepositoryRoot } from '@aiconfig/core/testing';
import { createDefaultAdapters } from '@aiconfig/providers';

import { runCli } from '../src/index.js';
import type { OutputStreams } from '../src/output.js';

const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const adapters = createDefaultAdapters();
const fileSystem = new NodeFileSystem();

/**
 * The CLI and the VS Code view are two front ends over one compiler, so every
 * operation one offers has to reach the other's result.
 *
 * Each case below runs the command and, in a second copy of the same project,
 * the core call the view makes — then compares the whole working tree. Testing
 * the message alone would let the two drift on what they actually do, which is
 * the half that matters.
 */

interface Captured {
  readonly streams: OutputStreams;
  stdout: () => string;
}

const capture = (): Captured => {
  let out = '';
  return {
    streams: {
      out: (line: string) => {
        out += `${line}\n`;
      },
      err: () => undefined,
    },
    stdout: () => out,
  };
};

let cliRoot = '';
let uiRoot = '';

const seed = (root: string): void => {
  fs.cpSync(path.join(exampleRepositoryRoot(testDirectory), '.ai'), path.join(root, '.ai'), {
    recursive: true,
    filter: (source) => path.basename(source) !== path.basename(MANIFEST_PATH),
  });
};

beforeEach(async () => {
  cliRoot = await fsp.mkdtemp(path.join(os.tmpdir(), 'aiconfig-parity-cli-'));
  uiRoot = await fsp.mkdtemp(path.join(os.tmpdir(), 'aiconfig-parity-ui-'));
  seed(cliRoot);
  seed(uiRoot);
});

afterEach(async () => {
  await fsp.rm(cliRoot, { recursive: true, force: true });
  await fsp.rm(uiRoot, { recursive: true, force: true });
});

const cli = async (args: readonly string[], root = cliRoot): Promise<string> => {
  const captured = capture();
  const code = await runCli([...args, '--cwd', root], { streams: captured.streams });
  expect(code, `${args.join(' ')} exited ${String(code)}`).toBe(0);
  return captured.stdout();
};

/** Every file in the tree, with its content, relative to the root. */
const treeOf = (root: string): Record<string, string> => {
  const files: Record<string, string> = {};
  const walk = (directory: string, prefix: string): void => {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const relative = prefix.length === 0 ? entry.name : `${prefix}/${entry.name}`;
      const nested = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        walk(nested, relative);
      } else if (entry.isFile()) {
        files[relative] = fs.readFileSync(nested, 'utf8');
      }
    }
  };
  walk(root, '');
  return files;
};

/**
 * Both trees, with the manifest excluded.
 *
 * The manifest records absolute-free paths and hashes, so it is identical
 * whenever the files are — comparing it too would only restate the assertion,
 * and it is regenerated by whichever operation ran last.
 */
const compare = (): { cli: Record<string, string>; ui: Record<string, string> } => ({
  cli: treeOf(cliRoot),
  ui: treeOf(uiRoot),
});

describe('the CLI reaches the same state as the view', () => {
  const KINDS: readonly { kind: SourceKind; name: string }[] = [
    { kind: 'instruction', name: 'general' },
    { kind: 'agent', name: 'reviewer' },
    { kind: 'skill', name: 'code-review' },
    { kind: 'command', name: 'fix-bug' },
  ];

  for (const { kind, name } of KINDS) {
    it(`removes a ${kind} exactly as Delete… does`, async () => {
      await cli(['sync']);
      await runCli(['sync', '--cwd', uiRoot], { streams: capture().streams });

      await cli(['remove', kind, name]);
      await cli(['sync']);

      // What the view runs: `removeArtifact`, then a synchronization.
      await removeArtifact(fileSystem, uiRoot, kind, name);
      await runCli(['sync', '--cwd', uiRoot], { streams: capture().streams });

      const trees = compare();
      expect(trees.cli).toEqual(trees.ui);
      expect(Object.keys(trees.cli).some((entry) => entry.includes(name))).toBe(false);
    });
  }

  it('removes the generated files exactly as Delete Generated Files does', async () => {
    await cli(['sync']);
    await runCli(['sync', '--cwd', uiRoot], { streams: capture().streams });

    await cli(['clean']);
    await clean(fileSystem, uiRoot, adapters);

    const trees = compare();
    expect(trees.cli).toEqual(trees.ui);
    // `.ai/` survives both, which is the whole point of the operation.
    expect(fs.existsSync(path.join(cliRoot, '.ai', 'config.yaml'))).toBe(true);
  });

  it('restores one generated file exactly as Restore Generated File does', async () => {
    const drifted = '.claude/agents/reviewer.md';
    await cli(['sync']);
    await runCli(['sync', '--cwd', uiRoot], { streams: capture().streams });

    for (const root of [cliRoot, uiRoot]) {
      fs.writeFileSync(path.join(root, ...drifted.split('/')), 'edited by hand', 'utf8');
    }

    await cli(['restore', drifted]);
    await restore(fileSystem, uiRoot, adapters, [drifted]);

    const trees = compare();
    expect(trees.cli).toEqual(trees.ui);
    expect(trees.cli[drifted]).not.toContain('edited by hand');
  });

  for (const provider of ['claude', 'opencode'] as const) {
    it(`disables and re-enables ${provider} exactly as the view does`, async () => {
      await cli(['providers', 'disable', provider]);
      await disableProvider(fileSystem, uiRoot, provider satisfies ProviderId);
      expect(compare().cli).toEqual(compare().ui);

      await cli(['providers', 'enable', provider]);
      await enableProvider(fileSystem, uiRoot, provider satisfies ProviderId);
      expect(compare().cli).toEqual(compare().ui);
    });
  }
});

describe('the new commands report what they did', () => {
  it('names every file a removal took', async () => {
    const output = await cli(['remove', 'agent', 'reviewer']);

    expect(output).toContain('.ai/agents/reviewer.md');
    // The overrides go with it, and are named too.
    expect(output).toContain('.ai/providers/claude/agents/reviewer.yaml');
    expect(output).toContain('Run: aiconfig sync');
  });

  it('says so when there was nothing to remove, without failing', async () => {
    // The view can only invoke this on a row it just drew; a shell cannot, so
    // a name that is not there is an ordinary answer rather than an error.
    const output = await cli(['remove', 'agent', 'nothing-here']);

    expect(output).toContain("No agent named 'nothing-here' exists.");
  });

  it('refuses a name that is not a canonical name', async () => {
    const captured = capture();
    const code = await runCli(['remove', 'agent', '../escape', '--cwd', cliRoot], {
      streams: captured.streams,
    });

    expect(code).toBe(1);
    expect(fs.existsSync(path.join(cliRoot, '.ai', 'agents', 'reviewer.md'))).toBe(true);
  });

  it('states that a disabled provider keeps its overrides', async () => {
    const output = await cli(['providers', 'disable', 'claude']);

    expect(output).toContain('.ai/providers/ are kept');
    expect(fs.existsSync(path.join(cliRoot, '.ai', 'providers', 'claude'))).toBe(true);
  });

  it('is a no-op, reported as one, when a provider is already enabled', async () => {
    const output = await cli(['providers', 'enable', 'claude']);

    expect(output).toContain("'claude' is already enabled.");
  });

  it('refuses a path it does not generate, as the view refuses the action', async () => {
    await cli(['sync']);
    const captured = capture();

    const code = await runCli(['restore', 'README.md', '--cwd', cliRoot], {
      streams: captured.streams,
    });

    expect(code).toBe(1);
  });

  it('emits the same JSON shape whether or not anything changed', async () => {
    await cli(['sync']);

    const removed = JSON.parse(await cli(['remove', 'agent', 'reviewer', '--json'])) as Record<
      string,
      unknown
    >;
    const absent = JSON.parse(await cli(['remove', 'agent', 'reviewer', '--json'])) as Record<
      string,
      unknown
    >;

    expect(Object.keys(removed).sort()).toEqual(Object.keys(absent).sort());
    expect(removed['ok']).toBe(true);
    expect(absent['removed']).toEqual([]);
  });
});

describe('init reports pre-existing provider files, as the view does', () => {
  it('lists them and explains that they stay with the author', async () => {
    const fresh = await fsp.mkdtemp(path.join(os.tmpdir(), 'aiconfig-parity-init-'));
    try {
      fs.mkdirSync(path.join(fresh, '.claude', 'agents'), { recursive: true });
      fs.writeFileSync(path.join(fresh, '.claude', 'agents', 'mine.md'), 'hand written', 'utf8');

      const output = await cli(['init'], fresh);

      // Directories, not files: ownership is provable only through the
      // manifest, so the report says what exists and claims nothing about it.
      expect(output).toContain('.claude/agents');
      expect(output).toContain('stay yours');
      // Reported, never touched.
      expect(fs.readFileSync(path.join(fresh, '.claude', 'agents', 'mine.md'), 'utf8')).toBe(
        'hand written',
      );
    } finally {
      await fsp.rm(fresh, { recursive: true, force: true });
    }
  });
});
