/**
 * The banner every file compiled from `.ai/instructions/` opens with.
 *
 * Shared rather than repeated per adapter because it names two things that can
 * change — the canonical directory and the command that regenerates it — and a
 * copy per adapter would let those drift without any test disagreeing: each
 * provider's golden output pins only its own copy.
 *
 * Not byte-identity-critical the way `AGENTS.md` is between Codex and OpenCode,
 * where the planner rejects a mismatch. This is one wording with more than one
 * destination; an adapter that needs a different banner declares its own.
 */
export const GENERATED_INSTRUCTIONS_HEADER = [
  '<!-- Generated by AI Config from .ai/instructions/. Do not edit directly. -->',
  '<!-- Edit the files under .ai/instructions/ and run `aiconfig sync`. -->',
].join('\n');
