import type { ProviderAdapter } from '../adapter/adapter.js';
import { GENERATION_RULES_PATH, renderGenerationRules } from '../docs/generation-rules.js';
import type { Diagnostic } from '../domain/diagnostic.js';
import type { ProviderId } from '../domain/provider.js';
import type { FileSystem } from '../fs/file-system.js';
import { AI_DIRECTORY } from '../parse/discover.js';
import { CONFIG_PATH, SUPPORTED_SCHEMA_VERSION } from '../parse/config.js';
import { checkPathsContained } from '../path/containment.js';
import { resolveWithinRoot } from '../path/safe-path.js';
import { renderMarkdownDocument } from '../text/yaml-frontmatter.js';

export const MANAGEMENT_INSTRUCTION_PATH = `${AI_DIRECTORY}/instructions/ai-config.md`;

const MANAGEMENT_INSTRUCTION_BODY = `This repository uses AI Config as the source of truth for AI assistant configuration.

Create, modify, rename, or remove agents, commands, instructions, and skills only through the corresponding canonical sources:

- \`.ai/agents/\`
- \`.ai/commands/\`
- \`.ai/instructions/\`
- \`.ai/skills/\`

Provider-specific settings belong under:

- \`.ai/providers/<provider>/\`

Do not directly edit files identified as generated by AI Config. This includes generated files under \`.agents/\`, \`.claude/\`, \`.codex/\`, \`.github/\`, and \`.opencode/\`, as well as generated \`CLAUDE.md\` and \`AGENTS.md\` files.

Not every file in these directories is necessarily managed by AI Config. Treat a file as generated only when it is identified by AI Config's generated-file manifest or generated header.

After changing a canonical source, run \`aiconfig sync\`. When the AI Config extension is active, synchronization may happen automatically.`;

export const MANAGEMENT_INSTRUCTION_CONTENT = renderMarkdownDocument(
  [['description', 'When creating or modifying AI assistant configuration']],
  MANAGEMENT_INSTRUCTION_BODY,
);

export interface InitOptions {
  readonly providers: readonly ProviderId[];
  /**
   * Adapters the generated reference is derived from.
   *
   * Required rather than optional: the reference is written by compiling a
   * probe with these, and an optional argument would let a caller drop the file
   * without noticing.
   */
  readonly adapters: readonly ProviderAdapter[];
  /** Recorded in the reference, so a stale one says which build wrote it. */
  readonly version: string;
}

export type InitOutcome =
  | { readonly ok: true; readonly created: readonly string[] }
  | { readonly ok: false; readonly diagnostics: readonly Diagnostic[] };

/**
 * Adds the standard management instruction to an existing project once.
 *
 * Existing content is always authoritative. The exclusive write also closes
 * the race between checking and creating, so an extension update cannot
 * replace a file that appeared while it was starting.
 */
export const ensureManagementInstruction = async (
  fileSystem: FileSystem,
  root: string,
): Promise<InitOutcome> => {
  const target = resolveWithinRoot(root, MANAGEMENT_INSTRUCTION_PATH);
  if (await fileSystem.exists(target)) {
    return { ok: true, created: [] };
  }

  const containment = await checkPathsContained(fileSystem, root, [
    AI_DIRECTORY,
    `${AI_DIRECTORY}/instructions`,
  ]);
  if (containment.length > 0) {
    return { ok: false, diagnostics: containment };
  }

  try {
    await fileSystem.writeFileAtomic(target, Buffer.from(MANAGEMENT_INSTRUCTION_CONTENT, 'utf8'), {
      exclusive: true,
    });
  } catch (error) {
    if (await fileSystem.exists(target)) {
      return { ok: true, created: [] };
    }
    throw error;
  }

  return { ok: true, created: [MANAGEMENT_INSTRUCTION_PATH] };
};

/**
 * Creates a starter `.ai/` directory.
 *
 * Refuses outright if `.ai/` already exists. Merging into an existing canonical
 * directory would mean deciding which of the user's files to replace, and that
 * decision is not AI Config's to make.
 *
 * The starter files are created exclusively, so that refusal also covers a path
 * that appears between the check and the write — a second `init` racing this
 * one, or an editor restoring a file. Checking once and writing later would
 * replace exactly the file this promises never to touch.
 */
export const init = async (
  fileSystem: FileSystem,
  root: string,
  options: InitOptions,
): Promise<InitOutcome> => {
  const aiPath = resolveWithinRoot(root, AI_DIRECTORY);

  if (await fileSystem.exists(aiPath)) {
    return {
      ok: false,
      diagnostics: [
        {
          code: 'ALREADY_INITIALIZED',
          severity: 'error',
          message: `'${AI_DIRECTORY}/' already exists. Remove it first if you want to start over.`,
          source: AI_DIRECTORY,
        },
      ],
    };
  }

  const files = [
    ...starterFiles(options.providers, options.adapters),
    {
      path: GENERATION_RULES_PATH,
      content: renderGenerationRules(options.adapters, options.version),
    },
  ];

  for (const directory of ['instructions', 'agents', 'skills', 'commands']) {
    await fileSystem.createDirectory(resolveWithinRoot(root, `${AI_DIRECTORY}/${directory}`));
  }
  // No provider directories. An override is user configuration, and an empty
  // '.ai/providers/<provider>/' suggests one exists where none does — for every
  // enabled provider at once, most of which will never get an override. The
  // directory is created with the first override written into it, so the tree
  // shows what is actually configured. Git does not track an empty directory
  // either, so these never survived a clone in the first place.

  for (const file of files) {
    try {
      await fileSystem.writeFileAtomic(
        resolveWithinRoot(root, file.path),
        Buffer.from(file.content, 'utf8'),
        { exclusive: true },
      );
    } catch {
      return {
        ok: false,
        diagnostics: [
          {
            code: 'ALREADY_INITIALIZED',
            severity: 'error',
            message: `'${file.path}' appeared while AI Config was initializing and was left alone. Remove '${AI_DIRECTORY}/' if you want to start over.`,
            source: file.path,
          },
        ],
      };
    }
  }

  return { ok: true, created: files.map((file) => file.path) };
};

interface StarterFile {
  readonly path: string;
  readonly content: string;
}

/** The canonical files every newly initialized project starts with. */
const starterFiles = (
  providers: readonly ProviderId[],
  adapters: readonly ProviderAdapter[],
): StarterFile[] => [
  { path: CONFIG_PATH, content: renderConfig(providers, adapters) },
  { path: MANAGEMENT_INSTRUCTION_PATH, content: MANAGEMENT_INSTRUCTION_CONTENT },
];

const renderConfig = (
  providers: readonly ProviderId[],
  adapters: readonly ProviderAdapter[],
): string => {
  const available = adapters
    .map((adapter) => adapter.id)
    .sort()
    .join(', ');
  const lines = [
    '# yaml-language-server: $schema=none',
    '# AI Config canonical configuration.',
    '# Specification: https://github.com/ShadyManu/ai-config/blob/main/docs/specification.md',
    ...(available.length === 0 ? [] : [`# Available providers: ${available}.`]),
    '',
    `schema: ${String(SUPPORTED_SCHEMA_VERSION)}`,
    '',
    'providers:',
  ];

  if (providers.length === 0) {
    lines.push('  enabled: []');
  } else {
    lines.push('  enabled:');
    for (const provider of [...providers].sort()) {
      lines.push(`    - ${provider}`);
    }
  }

  lines.push('');

  return lines.join('\n');
};
