import { describe, expect, it } from 'vitest';

import type { AiConfiguration, AiInstruction } from '@aiconfig/core';

import { AGENTS_MD_PATH, renderAgentsMarkdown } from '../src/index.js';

const instruction = (overrides: Partial<AiInstruction> & { name: string }): AiInstruction => ({
  description: undefined,
  applyTo: [],
  body: 'Body.',
  sourcePath: `.ai/instructions/${overrides.name}.md`,
  ...overrides,
});

const configurationOf = (instructions: readonly AiInstruction[]): AiConfiguration => ({
  instructions,
  agents: [],
  skills: [],
  commands: [],
});

const render = (instructions: readonly AiInstruction[]) =>
  renderAgentsMarkdown(configurationOf(instructions), 'codex', 'Codex');

describe('renderAgentsMarkdown', () => {
  it('renders a header and one section per instruction', () => {
    const result = render([
      instruction({ name: 'general', description: 'Project rules', body: 'Use pnpm.' }),
    ]);

    expect(result.path).toBe(AGENTS_MD_PATH);
    expect(result.content).toBe(
      [
        '<!-- Generated by AI Config from .ai/instructions/. Do not edit directly. -->',
        '<!-- Edit the files under .ai/instructions/ and run `aiconfig sync`. -->',
        '',
        '## general',
        '',
        'Project rules',
        '',
        'Use pnpm.',
        '',
      ].join('\n'),
    );
  });

  it('omits the description paragraph when there is none', () => {
    const result = render([instruction({ name: 'general', body: 'Use pnpm.' })]);

    expect(result.content).toContain('## general\n\nUse pnpm.\n');
    expect(result.diagnostics).toEqual([]);
  });

  it('states the scope in prose and warns that it is not enforced', () => {
    const result = render([
      instruction({ name: 'backend', applyTo: ['backend/**', 'services/**/*.ts'] }),
    ]);

    expect(result.content).toContain('Applies to: `backend/**`, `services/**/*.ts`');

    expect(result.diagnostics).toHaveLength(1);
    const diagnostic = result.diagnostics[0];
    expect(diagnostic?.code).toBe('INSTRUCTION_SCOPE_NOT_SUPPORTED');
    expect(diagnostic?.severity).toBe('warning');
    expect(diagnostic?.provider).toBe('codex');
    expect(diagnostic?.source).toBe('.ai/instructions/backend.md');
    expect(diagnostic?.message).toContain('backend/**, services/**/*.ts');
  });

  it('warns once per scoped instruction and not at all for unscoped ones', () => {
    const result = render([
      instruction({ name: 'a', applyTo: ['a/**'] }),
      instruction({ name: 'b' }),
      instruction({ name: 'c', applyTo: ['c/**'] }),
    ]);

    expect(result.diagnostics.map((d) => d.source)).toEqual([
      '.ai/instructions/a.md',
      '.ai/instructions/c.md',
    ]);
  });

  it('renders identical bytes whichever provider asked for it', () => {
    const configuration = configurationOf([
      instruction({ name: 'general', description: 'Rules', applyTo: ['src/**'] }),
    ]);

    // Codex and OpenCode both read this file, and the planner treats differing
    // content for one path as a hard error — so only the diagnostics may differ.
    const codex = renderAgentsMarkdown(configuration, 'codex', 'Codex');
    const opencode = renderAgentsMarkdown(configuration, 'opencode', 'OpenCode');

    expect(codex.content).toBe(opencode.content);
    expect(codex.path).toBe(opencode.path);
    expect(codex.diagnostics[0]?.provider).toBe('codex');
    expect(opencode.diagnostics[0]?.provider).toBe('opencode');
  });

  it('emits only the header when there are no instructions', () => {
    const result = render([]);

    expect(result.content).toBe(
      [
        '<!-- Generated by AI Config from .ai/instructions/. Do not edit directly. -->',
        '<!-- Edit the files under .ai/instructions/ and run `aiconfig sync`. -->',
        '',
      ].join('\n'),
    );
    expect(result.diagnostics).toEqual([]);
  });

  it('ends with exactly one newline', () => {
    const result = render([instruction({ name: 'general', body: 'Body.\n\n\n' })]);

    expect(result.content.endsWith('\n')).toBe(true);
    expect(result.content.endsWith('\n\n')).toBe(false);
  });

  it('preserves instruction order as given', () => {
    // Core sorts the IR once, so the renderer must not reorder.
    const result = render([
      instruction({ name: 'alpha' }),
      instruction({ name: 'beta' }),
      instruction({ name: 'gamma' }),
    ]);

    const headings = [...result.content.matchAll(/^## (.+)$/gm)].map((match) => match[1]);
    expect(headings).toEqual(['alpha', 'beta', 'gamma']);
  });

  it('does not let a description introduce a heading of its own', () => {
    const result = render([
      instruction({ name: 'general', description: 'Line one\n## Injected heading' }),
    ]);

    // The description is prose in the document, so a heading inside it is
    // rendered as-is — it cannot alter the section structure, because sections
    // are keyed by the instruction name.
    const headings = [...result.content.matchAll(/^## (.+)$/gm)].map((match) => match[1]);
    expect(headings[0]).toBe('general');
  });
});
